{% set version = "1.1.1" %}

package:
  name: earthsim
  version: v{{ version }}

source:
  url: https://github.com/pyviz/EarthSim/archive/v{{ version }}.tar.gz
  sha256: ac40292ebdfa6c620ac60b2fd0af771d1587e21cb15ea5ed8c07d5cf1edd35d6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - param = earthsim.__main__:param_main
    - earthsim = earthsim.__main__:main

requirements:
  build:
    # The python limitation is due to xmsmesher only being available on py36
    - python >=3.6,<3.7
    - pip
    - param >=1.7.0
    - pyct >=0.4.4
    - bokeh >=1.1.0
    - pyviz_comms >=0.6.0
    - nodejs >=9.11.1
  run:
    - python >=3.6,<3.7
    - param >=1.9.0,<2.0
    - holoviews >=1.12.3
    - datashader >=0.7.0
    - geoviews >=1.6.2
    - panel >=0.5.0
    - bokeh >=1.1.0
    - cartopy >=0.17.0
    - xarray >=0.11.0
    - colorcet >=1.0.0
    - notebook >=5.5.0
    - fiona
    - gdal >=2.4.0
    - rasterio >=1.0.13
    - xmscore
    - xmsinterp
    - xmsgrid
    # - xmsmesh this one is specified in the metadata.
    - xmsmesher

test:
  imports:
    - earthsim

about:
  home: https://github.com/pyviz/EarthSim
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Tools for working with and visualizing environmental simulations.'
  description: |
      Python-based tools for specifying, launching, visualizing, and analyzing environmental simulations, such as those for hydrology modeling.
      EarthSim is designed as a lightweight "overview" site and project, relying on core code maintained in other general-purpose PyViz projects.
  doc_url: https://pyviz.github.io/EarthSim/
  dev_url: https://github.com/pyviz/EarthSim

extra:
  recipe-maintainers:
    - ocefpaf
