{% set version = "1.1.1" %}

package:
  name: earthsim
  version: v{{ version }}

source:
  url: https://github.com/pyviz/EarthSim/archive/v{{ version }}.tar.gz
  sha256: ac40292ebdfa6c620ac60b2fd0af771d1587e21cb15ea5ed8c07d5cf1edd35d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - earthsim

about:
  home: https://github.com/pyviz/EarthSim
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Tools for working with and visualizing environmental simulations.'
  description: |
      Python-based tools for specifying, launching, visualizing, and analyzing environmental simulations, such as those for hydrology modeling.
      EarthSim is designed as a lightweight "overview" site and project, relying on core code maintained in other general-purpose PyViz projects.
  doc_url: https://pyviz.github.io/EarthSim/
  dev_url: https://github.com/pyviz/EarthSim

extra:
  recipe-maintainers:
    - ocefpaf
