travis:
  secure:
    BINSTAR_TOKEN: pO7GBvc/VkuGd/eMlUca0tFEMxW9TE8+A0kLWzspiZ3If1/k+WYdnwCEwXuWnAeqmi29UZB2ersNXD41Lwxw1a8UwcN4NRqsTGdYBZYqJLnKRjSXGXaiBmfxEWT+gxPHg2sDtr7G8Jje8+OOW28A0yDEBdf1Jvekl3P1jSZf52B4kBW/bapa/ZrD32mGc/AXggMeUr39nw2CShPwLCqUOtW+FhI25y+hN8W4RJ8F1aAlZsqBsc23x6KEzg/5whga+epkqJE1Gmqjltqnb0PMbrcQscRJjHzDjoOuIHNVWhlJu+FoRFSCP0P21xzM3n4rjK806Tzui2Ji7rhIW3iJHFrxgw3LjaLWSNFmMzX630QBk2NxhvN8WIR3Kl8NxPXB5uRhJtrfDVGw+1hkDlFX5qMEDg4ikVXoUWY74891mTIyeXbhI0noM+DQvafQ+hem67CH2YLQZDpW7aCrLNwuzGmMN50QVgplrig6EHfnf260M6snjp5pXriVSkXZ0TtHRi9rlGH6cVIZVw5Kf+FKE732u4wVaP51xvHqgcTaPsMtIQz833rV4DYPS/TTh1wKX6ZO6fTq2t/SYJHnROS80hGlXnv9cMpLGMuwq1ewolSZXGjGMnQ3gqHITEh8d5Jjl9nJQBsy2/VdmkvN5RwRfWErEaJJvBXXxfrauugcTps=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
