travis:
  secure:
    BINSTAR_TOKEN: 6tZmVQpd5ww6Ph2+YD3M4gBWBbLC/7bl4CsZMhhsy2Za9gkC3lThD+T7JUzVSzkEk5zG3Zia0OPE6Zr9IkQyViAUfrr/MNAoT3XFIatRfPdThJcyx+EqJVc2E9rgWOng3w5TktwfFSc5JVne4/ItQKGHvyHZ4d3sgG1MvaWGvDIyXm25CeIoYdnsTFcpkn4oghdYgFVAfALRUEJ3CL5q9KZE/pznhjVMp+xUU57i6Y7D/sEE7KCtD1wWuKVMu+61Z3CCERwZfya9zbTpdfzmpr6L03YAU4YLW8YctFzldxWIpZ43TmVc6DtUaDYR79ypIo2TdEzMkeMIQWFSg5bDnCL8VvB+tp4WK38KrQyNzdm+rR314ynSCQDHBtlWEZV3Y1d8loTfC2BYGEgMMkGmRck5RV8El6x9uCo3dxBwoUAfOy9mzJHneNQABtScTjImjOGjRvriCTBV67haTy7ruXMChc0BwKOrrPSzaybHA0/DLGzMoGetveUAXvZXHOD83Sp89q+vXRKV/O0624dw6S5FJarBjQ2Bs+xHdH4Tx69vi4XroFSR4lD8XbeRgsOl9vBooWPZIUnG7tQfVwRKRLZL/oWy8MwAV7IrogZVLvmgD1N9JBwaR6tvnZP2r6jY6GsSlO8272kvft7Gav9uvRzJXQwfpC7oY+jHPmiIIgk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
